# -*- coding: utf-8 -*-
"""ED-Twitter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tomWAZC5I938IhSy6VyjDEJunGr-e0PY

API Key: 9U6HwDLBJfI9ijdTywxF7jtLE
API Key Secret: 0nJ2GLxgZ5d8dR2CM1rcbZsR11eaFbZ2mJY1tB7mQRWM6lALDP
Bearer Token: AAAAAAAAAAAAAAAAAAAAACf4rAEAAAAA8zOXB%2B%2FL0EQHdIq5g2f%2FGWAHm6o%3D2dbs1kmpB6RgG5pARYpTuwibbovMva3Vrg0DBgrf8WqotQQXdJ
Access Token: 1711915345932435456-wO46bcjRehRCbGDyAXJAnJWKH8k0ts
Access Token Secret: pYR6JmOx86lqkFwNnMO7pWTl0QG9rBUoi4Qrr5COpTaAB
"""

pip install git+https://github.com/tweepy/tweepy.git

import tweepy
import pandas as pd

#consumer_key = "9U6HwDLBJfI9ijdTywxF7jtLE" # API/Consumer key
#consumer_secret = "0nJ2GLxgZ5d8dR2CM1rcbZsR11eaFbZ2mJY1tB7mQRWM6lALDP" # API/Consumer Secret Key
#access_token = "1711915345932435456-wO46bcjRehRCbGDyAXJAnJWKH8k0ts"    # Access Token key
#access_token_secret = "pYR6JmOx86lqkFwNnMO7pWTl0QG9rBUoi4Qrr5COpTaAB" # Access Token Secret key

# Pass twitter API authentication key
auth = tweepy.OAuth1UserHandler(
    consumer_key, consumer_secret,
    access_token, access_token_secret
)

# Instantiate tweepy API
api = tweepy.API(auth, wait_on_rate_limit=True)

search_query = "'thinspo''thinspiration''anorexia''bulimia''an0rex1a''edtwt''Ana'-filter:retweets AND -filter:replies AND -filter:links"
no_of_tweets = 1500

try:
    # Number of tweets to retrieve from search
    tweets = api.search_tweets(q=search_query, lang="en", count=no_of_tweets, tweet_mode ='extended')

    # Pulling some attributes from tweet
    attributes_container = [[tweet.user.name, tweet.country, tweet.created_at, tweet.favorite_count, tweet.source, tweet.full_text] for tweet in tweets]

    # Creation of column list to rename the columns in the dataframe
    columns = ["User", "Country", "Date Created", "Number of Likes", "Source of Tweet", "Tweet"]

    # Creation of dataframe
    tweets_df = pd.DataFrame(attributes_container, columns=columns)
except BaseException as e:
    print('Status Failed On,',str(e))

tweets_df

tweets[0]

from google.colab import files
tweets_df.to_csv('tweets.csv')
files.download('tweets.csv')